spring:
  datasource:
    url: jdbc:mysql://localhost:3306/companies
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
    generate-unique-name: false

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
